require('default.snippets.luasnip.go')
require('default.snippets.luasnip.lua')
require('default.snippets.luasnip.markdown')
require('default.snippets.luasnip.rust')
require('default.snippets.luasnip.typescriptreact')
require('luasnip.loaders.from_vscode').lazy_load()
